#! /usr/bin/env node
module.exports = {
  KALTURA_PLAYER_JS: 'kaltura-player-js',
  PLAYKIT_JS: 'playkit-js',
  LATEST: 'latest',
  DEV_MODE: 'devMode',
  RELEASE_MODE: 'releaseMode',
  LINK: 'link',
  VERSION: 'version',
  WATCH: 'watch',
  WORKING_ON: 'Working on: ',
  START_DEV_MODE: 'Starting Dev Mode',
  START_REL_MODE: 'Starting Release Mode',
  STOP_DEV_MODE: 'Stopping Dev Mode',
  COMMAND_NOT_FOUND: 'Command not found',
  BUILDING_FOR_CONFIGURATION: 'Building mode for configuration:',
  PACKAGE_JSON: 'package.json',
  CHANGELOG: 'CHANGELOG.md',
  DEPENDENCIES: 'dependencies',
  PEER_DEPENDENCIES: 'peerDependencies',
  DEV_DEPENDENCIES: 'devDependencies',
  START: 'start',
  STOP: 'stop',
  LOCAL: 'local',
  DEFAULT_CONFIG_PATH: process.env.PWD + '/lib/playkit-repos.json',
  GO: 'go',
  SKIP: 'skip'
};
