#! /usr/bin/env node
module.exports = {
  KALTURA_PLAYER_JS: 'kaltura-player-js',
  LATEST: 'latest',
  DEV_MODE: 'devMode',
  RELEASE_MODE: 'releaseMode',
  ENV_MANAGER: 'envManager',
  VERSION: 'version',
  WORKING_ON: 'Working on: ',
  START_DEV_MODE: 'Starting Dev Mode',
  START_REL_MODE: 'Starting Release Mode',
  STOP_DEV_MODE: 'Stopping Dev Mode',
  COMMAND_NOT_FOUND: 'Command not found',
  BUILDING_FOR_CONFIGURATION: 'Building mode for configuration:',
  PACKAGE_JSON: 'package.json',
  CHANGELOG: 'CHANGELOG.md',
  DEPENDENCIES: 'dependencies',
  PEER_DEPENDENCIES: 'peerDependencies',
  DEV_DEPENDENCIES: 'devDependencies',
  START: 'start',
  STOP: 'stop',
  LOCAL: 'local',
  RELEASE_NOTES_FILE_PATH: process.env.HOME + '/release-notes.txt',
  UTF_8: 'utf-8',
  KILLING_NODES: '✘ killing all node processes ✘',
  YARN_LOCK: 'yarn.lock',
  KALTURA_PLAYER_RELATIVE_PATH: '../../../kaltura-player-js/'
};
